# Generated by Django 4.0 on 2023-11-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_proyect_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='proyect',
            new_name='project',
        ),
    ]
